name:                synacor
version:             0.1.0.0
github:              "remusao/katas"
license:             BSD3
author:              "Rémi B."
maintainer:          "remi@cliqz.com"
copyright:           "2017 Rémi B."

# Metadata used when publishing your package
synopsis:            Solution to the Synacor challenge
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/remusao/katas#readme>

dependencies:
- base >= 4.7 && < 5

executables:
  synacor:
    main:                vm.hs
    source-dirs:         ./
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - containers
    - bytestring
    - vector
